### ISSUE TITLE
[Bug] Navigation for View Demo icons on Nucleo Icons section not working.

### ISSUE THREAD

**Issue by Zabeard** [creativetimofficial/paper-kit-react#1]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/paper-kit-react/#/index
### Operating System
Windows 10
### Device
Desktop Computer 
### Browser & Version
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
### Steps to reproduce
This is an issue on the Paper Kit React Live site:
Scroll down and click on View Demo Icons on the paper kit react live
### What is expected?
Navigation to  https://demos.creative-tim.com/paper-kit-react/#/nucleo-icons
### What is actually happening?
It navigated to https://demos.creative-tim.com/nucleo-icons instead which generated a 404 error.

---
### Solution
I can't fine if it's the version of the react router, since the SectionExamples.js link for Landing Page on line 47 works fine.  But the same thing in the nucleo icons doesn't. - Sorry not able to locate a solution at the moment.
### Additional comments
If you download and build the Paper Kit React on to machine, there is no problem because the page doesn't use # routing and is hosted at root so /nucleo-icons will work - landing page actually works works in both cases.  Happens also in Firefox latest also - it would appear to be react not rendering the link properly.

**Comment by Zabeard** [comment]
After having a looking the issue further, it looks link the links on the page as a whole (for non-external) are wrong, instead of :

`              <Button
                className="btn-round"
                color="danger"
                href="/nucleo-icons" 
                target="_blank"
              >
                View Demo Icons
              </Button>`

it should be:

`              <Link to="/nucleo-icons" target="_blank">
              <Button
                className="btn-round"
                color="danger"
              >
                View Demo Icons
              </Button></Link>`

This works if you use **HashRouter** or **BrowserRouter**

As I am new to React, this is my best guess.  Hope this helps.

**Comment by einazare** [comment]
Hello there, @Zabeard ,

Thank you for your interest in working with our products, and for noticing this issue.
Really sorry for this late response, I forgot to add this repository to my watch list to get notified when a new issue is opened.
The problem was because we were using a button with a href="/nucleo-icons" instead of a button with a href with the full path.

The issue was solved.

Best,
Manu
