### ISSUE TITLE
[Bug] Font resolving problems

### ISSUE THREAD

**Issue by Olegt0rr** [creativetimofficial/paper-kit-react#2]
### Version
latest from site
### Operating System
MacOS
### Device
Macbook Pro 13
### Browser & Version
Version 79.0.3945.88
### Steps to reproduce
1. Download .zip from site
2. Unpack
3. Install package.json
4. Run 

### What is actually happening?
Can't resolve './fonts/nucleo-icons.eot' in 'paper-kit-react-master/src/assets/scss'

---
### Solution
You need to edit 'src/assets/scss/paper-kit/_nucleo-icons.scss'
And add additional '../' to each path to font

**Comment by einazare** [comment]
Hello there, @Olegt0rr ,

Thank you for your interest in working with our products.
I've just made a quick test by following your exact steps:
1. Download .zip from site
2. Unpack
3. Install package.json
4. Run
On a MacBook PRO 15, and I did not have any issues.
Please make sure you have the latest version of NodeJS installed on your machine (v12.14.1 LTS - the Current version 13.6.0 always comes with new features, but also with bugs).

Best,
Manu

**Comment by tobilg** [comment]
I have the same issue, Node 12 LTS. It was fixed like @Olegt0rr described
