### ISSUE TITLE
[Bug] npm install broken

### ISSUE THREAD

**Issue by Pacanor** [creativetimofficial/paper-kit-react#9]
### Version
1.3.0
### Reproduction link
https://github.com/creativetimofficial/paper-kit-react
### Operating System
Win 10
### Device
HP Laptop
### Browser & Version
Brave Browser, 1.38.111
### Steps to reproduce
1. Download kit
2. Unzip kit
3. Open terminal inside root folder
4. Run npm install
### What is expected?
The app should install and be ready to demo
### What is actually happening?
I'm getting a dependency error.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: paper-kit-react@1.3.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.5.0" from react-datetime@3.0.4
npm ERR! node_modules/react-datetime
npm ERR!   react-datetime@"3.0.4" from the root project

---
### Solution
Currently running npm install --force to override the dependency issues. 
### Additional comments
I've noticed you have paper kit 2 for every platform except react. When will you be adding the latter?

**Comment by queenielyk** [comment]
I have got the same problem too!
Neither _npm install --force_ nor _npm install --legacy-peer-deps_ is working for me.
What should I do?

**Comment by sajadevo** [comment]
Hi guys,

This issue is fixed for v1.3.1

Best,
Sajad
